// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.13.0
// source: hermit-shell-grpc/grpc/hermit-shell.proto

package hermit_shell_grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name.
type SubscribeEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventName string `protobuf:"bytes,1,opt,name=eventName,proto3" json:"eventName,omitempty"`
}

func (x *SubscribeEventRequest) Reset() {
	*x = SubscribeEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hermit_shell_grpc_grpc_hermit_shell_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeEventRequest) ProtoMessage() {}

func (x *SubscribeEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hermit_shell_grpc_grpc_hermit_shell_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeEventRequest.ProtoReflect.Descriptor instead.
func (*SubscribeEventRequest) Descriptor() ([]byte, []int) {
	return file_hermit_shell_grpc_grpc_hermit_shell_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeEventRequest) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

// The response message containing the greetings
type SubscribeEventReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload string `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *SubscribeEventReply) Reset() {
	*x = SubscribeEventReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hermit_shell_grpc_grpc_hermit_shell_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeEventReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeEventReply) ProtoMessage() {}

func (x *SubscribeEventReply) ProtoReflect() protoreflect.Message {
	mi := &file_hermit_shell_grpc_grpc_hermit_shell_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeEventReply.ProtoReflect.Descriptor instead.
func (*SubscribeEventReply) Descriptor() ([]byte, []int) {
	return file_hermit_shell_grpc_grpc_hermit_shell_proto_rawDescGZIP(), []int{1}
}

func (x *SubscribeEventReply) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

var File_hermit_shell_grpc_grpc_hermit_shell_proto protoreflect.FileDescriptor

var file_hermit_shell_grpc_grpc_hermit_shell_proto_rawDesc = []byte{
	0x0a, 0x29, 0x68, 0x65, 0x72, 0x6d, 0x69, 0x74, 0x2d, 0x73, 0x68, 0x65, 0x6c, 0x6c, 0x2d, 0x67,
	0x72, 0x70, 0x63, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x68, 0x65, 0x72, 0x6d, 0x69, 0x74, 0x2d,
	0x73, 0x68, 0x65, 0x6c, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x69, 0x6f, 0x2e,
	0x68, 0x65, 0x72, 0x6d, 0x69, 0x74, 0x2e, 0x73, 0x68, 0x65, 0x6c, 0x6c, 0x22, 0x35, 0x0a, 0x15,
	0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x4e,
	0x61, 0x6d, 0x65, 0x22, 0x2f, 0x0a, 0x13, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x32, 0x76, 0x0a, 0x10, 0x48, 0x65, 0x72, 0x6d, 0x69, 0x74, 0x53, 0x68,
	0x65, 0x6c, 0x6c, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x62, 0x0a, 0x0e, 0x53, 0x75, 0x62, 0x73,
	0x63, 0x72, 0x69, 0x62, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x26, 0x2e, 0x69, 0x6f, 0x2e,
	0x68, 0x65, 0x72, 0x6d, 0x69, 0x74, 0x2e, 0x73, 0x68, 0x65, 0x6c, 0x6c, 0x2e, 0x53, 0x75, 0x62,
	0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x24, 0x2e, 0x69, 0x6f, 0x2e, 0x68, 0x65, 0x72, 0x6d, 0x69, 0x74, 0x2e, 0x73,
	0x68, 0x65, 0x6c, 0x6c, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x30, 0x01, 0x42, 0x4b, 0x0a, 0x14,
	0x69, 0x6f, 0x2e, 0x68, 0x65, 0x72, 0x6d, 0x69, 0x74, 0x2d, 0x73, 0x68, 0x65, 0x6c, 0x6c, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x42, 0x0a, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x50, 0x01, 0x5a, 0x25, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61,
	0x2d, 0x69, 0x6e, 0x61, 0x63, 0x69, 0x6f, 0x2f, 0x68, 0x65, 0x72, 0x6d, 0x69, 0x74, 0x2d, 0x73,
	0x68, 0x65, 0x6c, 0x6c, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_hermit_shell_grpc_grpc_hermit_shell_proto_rawDescOnce sync.Once
	file_hermit_shell_grpc_grpc_hermit_shell_proto_rawDescData = file_hermit_shell_grpc_grpc_hermit_shell_proto_rawDesc
)

func file_hermit_shell_grpc_grpc_hermit_shell_proto_rawDescGZIP() []byte {
	file_hermit_shell_grpc_grpc_hermit_shell_proto_rawDescOnce.Do(func() {
		file_hermit_shell_grpc_grpc_hermit_shell_proto_rawDescData = protoimpl.X.CompressGZIP(file_hermit_shell_grpc_grpc_hermit_shell_proto_rawDescData)
	})
	return file_hermit_shell_grpc_grpc_hermit_shell_proto_rawDescData
}

var file_hermit_shell_grpc_grpc_hermit_shell_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_hermit_shell_grpc_grpc_hermit_shell_proto_goTypes = []interface{}{
	(*SubscribeEventRequest)(nil), // 0: io.hermit.shell.SubscribeEventRequest
	(*SubscribeEventReply)(nil),   // 1: io.hermit.shell.SubscribeEventReply
}
var file_hermit_shell_grpc_grpc_hermit_shell_proto_depIdxs = []int32{
	0, // 0: io.hermit.shell.HermitShellEvent.SubscribeEvent:input_type -> io.hermit.shell.SubscribeEventRequest
	1, // 1: io.hermit.shell.HermitShellEvent.SubscribeEvent:output_type -> io.hermit.shell.SubscribeEventReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_hermit_shell_grpc_grpc_hermit_shell_proto_init() }
func file_hermit_shell_grpc_grpc_hermit_shell_proto_init() {
	if File_hermit_shell_grpc_grpc_hermit_shell_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_hermit_shell_grpc_grpc_hermit_shell_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscribeEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hermit_shell_grpc_grpc_hermit_shell_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscribeEventReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hermit_shell_grpc_grpc_hermit_shell_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hermit_shell_grpc_grpc_hermit_shell_proto_goTypes,
		DependencyIndexes: file_hermit_shell_grpc_grpc_hermit_shell_proto_depIdxs,
		MessageInfos:      file_hermit_shell_grpc_grpc_hermit_shell_proto_msgTypes,
	}.Build()
	File_hermit_shell_grpc_grpc_hermit_shell_proto = out.File
	file_hermit_shell_grpc_grpc_hermit_shell_proto_rawDesc = nil
	file_hermit_shell_grpc_grpc_hermit_shell_proto_goTypes = nil
	file_hermit_shell_grpc_grpc_hermit_shell_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// HermitShellEventClient is the client API for HermitShellEvent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HermitShellEventClient interface {
	SubscribeEvent(ctx context.Context, in *SubscribeEventRequest, opts ...grpc.CallOption) (HermitShellEvent_SubscribeEventClient, error)
}

type hermitShellEventClient struct {
	cc grpc.ClientConnInterface
}

func NewHermitShellEventClient(cc grpc.ClientConnInterface) HermitShellEventClient {
	return &hermitShellEventClient{cc}
}

func (c *hermitShellEventClient) SubscribeEvent(ctx context.Context, in *SubscribeEventRequest, opts ...grpc.CallOption) (HermitShellEvent_SubscribeEventClient, error) {
	stream, err := c.cc.NewStream(ctx, &_HermitShellEvent_serviceDesc.Streams[0], "/io.hermit.shell.HermitShellEvent/SubscribeEvent", opts...)
	if err != nil {
		return nil, err
	}
	x := &hermitShellEventSubscribeEventClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type HermitShellEvent_SubscribeEventClient interface {
	Recv() (*SubscribeEventReply, error)
	grpc.ClientStream
}

type hermitShellEventSubscribeEventClient struct {
	grpc.ClientStream
}

func (x *hermitShellEventSubscribeEventClient) Recv() (*SubscribeEventReply, error) {
	m := new(SubscribeEventReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// HermitShellEventServer is the server API for HermitShellEvent service.
type HermitShellEventServer interface {
	SubscribeEvent(*SubscribeEventRequest, HermitShellEvent_SubscribeEventServer) error
}

// UnimplementedHermitShellEventServer can be embedded to have forward compatible implementations.
type UnimplementedHermitShellEventServer struct {
}

func (*UnimplementedHermitShellEventServer) SubscribeEvent(*SubscribeEventRequest, HermitShellEvent_SubscribeEventServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeEvent not implemented")
}

func RegisterHermitShellEventServer(s *grpc.Server, srv HermitShellEventServer) {
	s.RegisterService(&_HermitShellEvent_serviceDesc, srv)
}

func _HermitShellEvent_SubscribeEvent_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeEventRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HermitShellEventServer).SubscribeEvent(m, &hermitShellEventSubscribeEventServer{stream})
}

type HermitShellEvent_SubscribeEventServer interface {
	Send(*SubscribeEventReply) error
	grpc.ServerStream
}

type hermitShellEventSubscribeEventServer struct {
	grpc.ServerStream
}

func (x *hermitShellEventSubscribeEventServer) Send(m *SubscribeEventReply) error {
	return x.ServerStream.SendMsg(m)
}

var _HermitShellEvent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "io.hermit.shell.HermitShellEvent",
	HandlerType: (*HermitShellEventServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeEvent",
			Handler:       _HermitShellEvent_SubscribeEvent_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "hermit-shell-grpc/grpc/hermit-shell.proto",
}
